// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initializer

import (
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator"
	"go-base/internal/adapter/http/route"
	"go-base/internal/domain/usecase"
	"go-base/internal/infrastructure/database"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeExample(router *gin.Engine, db *gorm.DB, validate *validator.Validate) route.ExampleRoute {
	exampleRepository := database.ProviderExampleRepository(db, validate)
	exampleUseCase := usecase.ProviderExampleUseCase(exampleRepository)
	exampleRoute := route.ProviderExamplehRoute(router, exampleUseCase)
	return exampleRoute
}

func InitializeHealth(router *gin.Engine) route.HealthRoute {
	healthRoute := route.ProviderHealthRoute(router)
	return healthRoute
}
